app = "todomvc-022"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start = true
  auto_stop = "stop"

[mounts]
  source = "data"
  destination = "/app/data"
